sudo: required
services:
  - docker

before_install:
  -docker build -t shashwatmath/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shashwatmath/react-test npm test -- --watchAll

after_success:
  - docker build -t shashwatmath/multi-client ./client
  - docker build -t shashwatmath/multi-nginx ./nginx
  - docker build -t shashwatmath/multi-server ./server
  - docker build -t shashwatmath/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to docker hub
  - docker push shashwatmath/multi-client
  - docker push shashwatmath/multi-nginx
  - docker push shashwatmath/multi-server
  - docker push shashwatmath/multi-worker